### PR TITLE
adds support for java 21

### PR DESCRIPTION
**Pull request by Taz03**
Requires [eclipse-jdtls/eclipse.jdt.ls#2863](https://github.com/eclipse-jdtls/eclipse.jdt.ls/pull/2863)

### CODE REVIEW

**Comment by g-suraj** [comment]
@chemzqm Could you please cut a release for this change?

**Comment by meredrica** [comment]
@chemzqm is there any plan on a release? it's been 5 months

**Comment by Taz03** [comment]
@meredrica the project is dead

**Comment by sainnhe** [comment]
For anyone who wants to get java 21/22 support, you can try my branch https://github.com/neoclide/coc-java/pull/286

**Pull request merged**
